FROM ubuntu:latest

RUN apt-get update
RUN apt-get purge python
RUN apt-get autoremove -y
RUN apt-get install -y python3.4 python3-pip python3-dev
RUN apt-get build-dep -y pillow

WORKDIR /app/
ADD requirements-web.txt /app/requirements-web.txt
RUN pip3 install -r /app/requirements-web.txt
RUN pip3 install flake8

ADD . /app/
RUN flake8 pmweb
