# Base image
printermood:
    build: .
    volumes:
        - .:/app/

# Implementations of the base image
cam:
    extends: 
        file: docker-compose.yml
        service: printermood
    privileged: true
    environment:
        - DISPLAY=:0.0
    volumes:
        - '/tmp/.X11-unix:/tmp/.X11-unix'
    command: python printermood/cam.py --cascade printermood/haarcascade_frontalface_default.xml --preview

test:
    extends: 
        file: docker-compose.yml
        service: printermood
    links:
        - mongo
    environment:
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
    command: nosetests

# External libs
mongo:
    restart: always
    expose:
        - "27017"
    image: mongo

